name: The Morning Writer
description: Morning Pages. Every Day.
meta_description: "Morning Pages. Every Day"

markdown: markdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
permalink:   /blog/:title
domain_name: 'https://www.themorningwriter.com/'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'https://www.themorningwriter.com/'
author:         'The Morning Writer'


gems:
  - jekyll-sitemap
  - jekyll-paginate
